# Generated by Django 6.1.2 on 2026-10-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('customer_id', models.UUIDField(db_index=True)),
                ('agent_id', models.UUIDField(db_index=True)),
                ('manager_id', models.UUIDField(db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=16)),
                ('opened_at', models.DateTimeField()),
                ('assigned_at', models.DateTimeField()),
                ('awaiting_agent_since', models.DateTimeField(null=True)),
                ('awaiting_customer_since', models.DateTimeField(null=True)),
                ('escalated_at', models.DateTimeField(null=True)),
                ('opened_by_agent_since_escalation', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ticketing_ticket',
                'indexes': [models.Index(fields=['status', 'awaiting_customer_since'], name='ticketing_t_status_c10fac_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('author_role', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent')], max_length=16)),
                ('author_id', models.UUIDField()),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticketing.ticketrecord')),
            ],
            options={
                'db_table': 'ticketing_message',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'position'), name='unique_message_position')],
            },
        ),
    ]
