# Generated by Django 6.1.2 on 2026-10-09 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='support_agent', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('manager', 'Manager')], default='agent', max_length=16)),
                ('is_available', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='support_team.agent')),
            ],
        ),
    ]
